const quizQuestions = [
    // --- FILE I/O (TESTO E BINARI) ---
    { id: "q_file_1", category: "File I/O", text: "Come viene utilizzato il buffer nelle operazioni di I/O?", options: ["Il buffer cripta i dati.", "È un'area RAM temporanea che accumula dati per ridurre accessi lenti al disco.", "Svuota il file all'apertura.", "Converte il C++ in macchina."], correctAnswer: 1, explanation: "Il buffer riduce il numero di accessi fisici al disco raggruppando i dati in blocchi in RAM.", visualType: "buffer" },
    { id: "q_file_2", category: "File I/O", text: "Codice per scrivere in un file di testo?", options: ["cin >> file(\"dati.txt\");", "ofstream file(\"dati.txt\"); if(file.is_open()) { file << \"Dati\"; file.close(); }", "FileWrite fw;", "fstream file.read();"], correctAnswer: 1, explanation: "Si usa ofstream. L'operatore << manda dati nello stream, e close() scarica il buffer." },
    { id: "q_file_3", category: "File I/O", text: "Come verificare l'apertura di un file?", options: ["if(file.error())", "if(!file.is_open()) { cout << \"Errore\"; }", "try { file.open(); }", "if(file == null)"], correctAnswer: 1, explanation: "is_open() restituisce true se lo stream è associato a un file fisico valido." },
    { id: "q_file_4", category: "File I/O", text: "Metodo per leggere un singolo carattere (inclusi spazi)?", options: ["get()", "getline()", "readChar()", ">>"], correctAnswer: 0, explanation: "get() estrae esattamente un char, mentre >> ignorerebbe gli spazi o i ritorni a capo." },
    { id: "q_file_5", category: "File I/O", text: "Modalità per appendere dati alla fine di un file?", options: ["fstream::in", "fstream::out", "fstream::app", "fstream::trunc"], correctAnswer: 2, explanation: "app (Append) aggiunge dati in coda preservando il contenuto precedente." },
    { id: "q_file_6", category: "File I/O", text: "Modalità che cancella il contenuto esistente?", options: ["ios::in", "ios::out", "ios::app", "ios::ate"], correctAnswer: 1, explanation: "ios::out (di default) crea o tronca il file." },
    { id: "q_file_7", category: "File I/O", text: "Classe per gestire SIA lettura che scrittura?", options: ["ifstream", "ofstream", "fstream", "streamIO"], correctAnswer: 2, explanation: "fstream eredita da entrambi e permette I/O combinato." },
    { id: "q_file_8", category: "File I/O", text: "Metodo per verificare la fine del file?", options: ["eof()", "is_done()", "end()", "good()"], correctAnswer: 0, explanation: "eof() restituisce true quando si tenta di leggere oltre la fine." },
    { id: "q_file_9", category: "File I/O", text: "La gestione fisica di un file su disco spetta a:", options: ["Programma C++", "Sistema Operativo", "Directory", "CPU"], correctAnswer: 1, explanation: "Il Sistema Operativo astrae la scrittura sull'hardware." },
    { id: "q_file_10", category: "File I/O", text: "Perché nei file binari si usa char nome[30] e NON std::string?", options: ["std::string è lento.", "std::string richiede librerie.", "Nei binari serve una dimensione fissa (sizeof) fissa, string usa puntatori dinamici.", "C++ non supporta string."], correctAnswer: 2, explanation: "string scriverebbe indirizzi RAM nel file, perdendo il testo reale." },
    { id: "q_file_11", category: "File I/O", text: "Come si scrive un record 'buffer' in binario?", options: ["f.write(buffer);", "f.write((char*)&buffer, sizeof(buffer));", "f << buffer;", "write(f, buffer);"], correctAnswer: 1, explanation: "write vuole l'indirizzo castato a char* e la dimensione in byte." },
    { id: "q_file_12", category: "File I/O", text: "A cosa serve f.seekg()?", options: ["Cancellare record.", "Spostare cursore di LETTURA.", "Spostare cursore di SCRITTURA.", "Leggere la dimensione."], correctAnswer: 1, explanation: "seekg (seek get) sposta lettura, seekp (seek put) sposta scrittura." },
    { id: "q_file_13", category: "File I/O", text: "Come mi riposiziono per sovrascrivere il record APPENA LETTO?", options: ["f.seekp(f.tellg());", "f.seekp(f.tellg() + sizeof(buffer));", "f.seekp(f.tellg() - sizeof(buffer));", "f.write();"], correctAnswer: 2, explanation: "Devi tornare indietro (sottrarre sizeof) dal tellg attuale." },
    { id: "q_file_14", category: "File I/O", text: "Tecnica per CANCELLARE un record a metà file?", options: ["f.deleteRecord()", "Sovrascrivere con zeri", "Creare file appoggio, copiare i record tranne quello da eliminare, rimpiazzare l'originale.", "clear()"], correctAnswer: 2, explanation: "Il file system non 'accorcia' al centro, serve un travaso su file temporaneo." },

    // --- VETTORI ---
    { id: "q_vet_1", category: "Vettori", text: "Cosa accade se in int v[5] accedo a v[5]?", options: ["Eccezione catchabile.", "Restituisce 0.", "Buffer overflow: leggo memoria fuori dall'array.", "Si ridimensiona a 6."], correctAnswer: 2, explanation: "Gli indici vanno da 0 a 4. v[5] accede a memoria sconosciuta!" },
    { id: "q_vet_2", category: "Vettori", text: "Codice per stampare un array N in ordine inverso?", options: ["for(int i=0; i<N; i--) cout << v[i];", "for(int i=N; i>=0; i--) cout << v[i];", "for(int i=N-1; i>=0; i--) cout << v[i];", "for(int i=N; i>0; i++) cout << v[i];"], correctAnswer: 2, explanation: "Si parte da N-1 e si scende fino a 0 incluso (>= 0)." },
    { id: "q_vet_3", category: "Vettori", text: "Come modificare solo gli elementi in INDICI dispari in un array?", options: ["if (v[i] % 2 != 0)", "if (i % 2 != 0) v[i] += 100;", "if (i % 2 == 0)", "if (v[i] % 2 == 0)"], correctAnswer: 1, explanation: "L'indice è 'i', il valore è 'v[i]'. 'i % 2 != 0' controlla se la posizione è dispari." },
    { id: "q_vet_4", category: "Vettori", text: "Cosa fa: c[i] = a[i] + b[i]; in un ciclo?", options: ["Somma gli elementi di a.", "Fonde gli array in coda.", "Somma due array paralleli elemento per elemento.", "Errore di sintassi."], correctAnswer: 2, explanation: "È un algoritmo classico di somma tra vettori paralleli." },
    { id: "q_vet_5", category: "Vettori", text: "Come trovo la parola più lunga in un array di stringhe?", options: ["for(i=1; i<size; i++) if(arr[i].length() > arr[maxIdx].length()) maxIdx = i;", "sizeof(arr[i])", "if(arr[i] > arr[maxIdx])", "if(maxIdx > size)"], correctAnswer: 0, explanation: "Si usa il metodo .length() sulle stringhe e si salva l'indice maxIdx." },
    { id: "q_vet_6", category: "Vettori", text: "Cos'è un Vettore in memoria?", options: ["Una lista concatenata di puntatori.", "Un blocco di memoria contiguo.", "Un file temporaneo.", "Una funzione."], correctAnswer: 1, explanation: "Gli array nativi del C++ sono blocchi di memoria sequenziali e continui." },

    // --- MATRICI ---
    { id: "q_mat_1", category: "Matrici", text: "Come dichiarare e riempire a ZERI una matrice 10x5?", options: ["int m[5][10] = 0;", "int m[10, 5];", "int m[10][5] = {};", "matrix<int> m(10,5);"], correctAnswer: 2, explanation: "{} è l'inizializzazione standard per azzerare un array multidimensionale in C++." },
    { id: "q_mat_2", category: "Matrici", text: "Cicli ottimali per stampare una matrice intera?", options: ["Solo riga * colonna.", "Esterno (i) per le righe, interno (j) per colonne. mat[i][j]", "Esterno colonne (j), interno righe (i). mat[j][i]", "Indifferente per RAM."], correctAnswer: 1, explanation: "Essendo in Row-Major order, scorrere prima la riga e poi la colonna sfrutta la cache della CPU." },
    { id: "q_mat_3", category: "Matrici", text: "Codice riga somma massima in matrice 4x4?", options: ["for(i) { sum=0; for(j) sum+=m[i][j]; if(sum>max) max=sum; }", "sum+=m[i][i]", "if(m[i][j] > max)", "Impossibile"], correctAnswer: 0, explanation: "Si azzera la somma all'inizio della riga (ciclo esterno) e si fa il totale scorrendo la colonna." },
    { id: "q_mat_4", category: "Matrici", text: "Cosa restituisce m[2][3] in una matrice dichiarata int m[5][5]?", options: ["Terza riga, quarta colonna.", "Seconda riga, terza colonna.", "Errore.", "Puntatore a riga 2."], correctAnswer: 0, explanation: "Gli indici partono da 0. Indice 2 = terza riga, Indice 3 = quarta colonna." },
    { id: "q_mat_5", category: "Matrici", text: "Come sommare tutti gli elementi della Diagonale Principale di una matrice N x N?", options: ["for(i=0; i<N; i++) sum += m[i][0];", "for(i=0; i<N; i++) sum += m[i][i];", "for(i=0; i<N; i++) sum += m[i][N-i];", "for(i=0; i<N; i++) sum += m[0][i];"], correctAnswer: 1, explanation: "Nella diagonale principale gli indici di riga e colonna sono uguali (es. 0,0 - 1,1 - 2,2)." },

    // --- GENERAZIONE NUMERI (<cstdlib>) ---
    { id: "q_rnd_1", category: "Generazione Numeri", text: "Come inizializzare il generatore di numeri casuali?", options: ["random_start()", "rand(time())", "srand(time(NULL));", "random.seed()"], correctAnswer: 2, explanation: "srand() inizializza il Seed (seme). time(NULL) garantisce un seme diverso ad ogni esecuzione." },
    { id: "q_rnd_2", category: "Generazione Numeri", text: "Librerie necessarie per usare srand e time?", options: ["<random> e <time>", "<cstdlib> e <ctime>", "<math> e <std>", "<iostream> e <stdlib>"], correctAnswer: 1, explanation: "<cstdlib> contiene rand/srand, <ctime> contiene time()." },
    { id: "q_rnd_3", category: "Generazione Numeri", text: "Come estrarre un numero casuale compreso tra 0 e 9?", options: ["rand(10)", "rand() / 10", "rand() % 10", "rand() % 9"], correctAnswer: 2, explanation: "L'operatore Modulo % restituisce il resto della divisione intera, che per 10 va da 0 a 9." },
    { id: "q_rnd_4", category: "Generazione Numeri", text: "Cosa succede se NON metto srand(time(NULL)) ma chiamo solo rand()?", options: ["Errore di compilazione.", "Il programma crasherà.", "Restituisce sempre 0.", "Genererà la stessa identica sequenza di numeri ad ogni avvio del programma."], correctAnswer: 3, explanation: "Senza un seme dinamico, rand() parte sempre dal seme predefinito (1), risultando deterministico e ripetitivo." },
    { id: "q_rnd_5", category: "Generazione Numeri", text: "Come estrarre un numero compreso tra 10 e 50 inclusi?", options: ["rand() % 50 + 10", "rand() % 41 + 10", "rand(10, 50)", "(rand() % 40) + 10"], correctAnswer: 1, explanation: "Il range è (50-10+1) = 41. Quindi `rand() % 41` genera da 0 a 40. Aggiungendo 10 shiftiamo il range a [10, 50]." },

    // --- CIRCUITI RLC ---
    { id: "q_rlc_1", category: "Circuiti RLC", text: "Quali sono i tre componenti fondamentali di un circuito RLC?", options: ["Relè, Lampada, Condensatore", "Resistore, Induttore, Condensatore", "Raddrizzatore, Invertitore, Cavo", "Resistore, Led, Circuito integrato"], correctAnswer: 1, explanation: "R = Resistore, L = Induttore, C = Condensatore." },
    { id: "q_rlc_2", category: "Circuiti RLC", text: "Come si comporta un condensatore in Corrente Continua (CC) a regime?", options: ["Come un cortocircuito", "Come un resistore", "Come un circuito aperto", "Oscilla"], correctAnswer: 2, explanation: "Una volta carico, il condensatore blocca il passaggio di CC comportandosi come un circuito aperto." },
    { id: "q_rlc_3", category: "Circuiti RLC", text: "Cos'è la Risonanza in un circuito RLC?", options: ["La frequenza in cui il circuito si spegne.", "La frequenza in cui reattanza induttiva e capacitiva si annullano a vicenda.", "Il suono emesso dall'induttore.", "La massima opposizione al passaggio di corrente."], correctAnswer: 1, explanation: "In risonanza, gli effetti reattivi opposti di induttore e condensatore si cancellano." },
    { id: "q_rlc_4", category: "Circuiti RLC", text: "Qual è l'unità di misura dell'Induttanza (L)?", options: ["Farad (F)", "Ohm (Ω)", "Henry (H)", "Volt (V)"], correctAnswer: 2, explanation: "L'induttanza si misura in Henry (H)." },

    // --- PORTE LOGICHE ---
    { id: "q_log_1", category: "Porte Logiche", text: "Quale porta logica dà in uscita 1 SOLO SE tutti i suoi ingressi sono 1?", options: ["OR", "AND", "XOR", "NOT"], correctAnswer: 1, explanation: "La porta AND rappresenta il prodotto logico, quindi 1 * 1 = 1, ma 1 * 0 = 0." },
    { id: "q_log_2", category: "Porte Logiche", text: "Cosa fa una porta NOT?", options: ["Somma gli ingressi.", "Lascia invariato il segnale.", "Inverte il segnale in ingresso (0 diventa 1, 1 diventa 0).", "Blocca la corrente."], correctAnswer: 2, explanation: "La porta NOT è un invertitore logico." },
    { id: "q_log_3", category: "Porte Logiche", text: "Quando una porta XOR (OR Esclusivo) restituisce 1?", options: ["Quando gli ingressi sono tutti 0.", "Quando gli ingressi sono tutti 1.", "Quando gli ingressi sono DIVERSI tra loro.", "Sempre."], correctAnswer: 2, explanation: "L'OR esclusivo esclude il caso in cui entrambi gli ingressi siano uguali. Quindi (0,1) e (1,0) danno 1." },
    { id: "q_log_4", category: "Porte Logiche", text: "Perché NAND e NOR sono dette porte 'universali'?", options: ["Perché si usano in tutto l'universo.", "Perché costano meno.", "Perché combinandole si può creare qualsiasi altra porta logica o circuito digitale.", "Perché accettano segnali analogici."], correctAnswer: 2, explanation: "Tramite opportune configurazioni di sole NAND (o sole NOR) è possibile ricreare AND, OR, NOT ecc." },

    // --- DIODI E PONTE DI GRAETZ ---
    { id: "q_dio_1", category: "Diodi e Ponte di Graetz", text: "Qual è la funzione principale di un diodo?", options: ["Amplificare il segnale.", "Memorizzare energia.", "Permettere il passaggio di corrente in una sola direzione.", "Generare corrente."], correctAnswer: 2, explanation: "Il diodo conduce solo se polarizzato direttamente, comportandosi come una valvola di non ritorno." },
    { id: "q_dio_2", category: "Diodi e Ponte di Graetz", text: "Quali sono i terminali del diodo?", options: ["Base, Collettore, Emettitore", "Anodo (+) e Catodo (-)", "Positivo, Negativo e Terra", "Drain e Source"], correctAnswer: 1, explanation: "L'Anodo è la zona P (positiva), il Catodo è la zona N (negativa)." },
    { id: "q_dio_3", category: "Diodi e Ponte di Graetz", text: "Quanti diodi servono per formare un Ponte di Graetz?", options: ["1", "2", "4", "8"], correctAnswer: 2, explanation: "Il ponte di Graetz standard utilizza 4 diodi disposti a rombo." },
    { id: "q_dio_4", category: "Diodi e Ponte di Graetz", text: "A cosa serve il condensatore posto in uscita a un Ponte di Graetz?", options: ["A fare luce.", "A creare corrente alternata.", "A livellare ('spianare') la tensione raddrizzata per ottenere una Corrente Continua stabile.", "A limitare la corrente massima."], correctAnswer: 2, explanation: "Il ponte raddrizza le semionde, ma il segnale è pulsante. Il condensatore di livellamento si carica e si scarica lentamente colmando i 'buchi' di tensione." }
];
